# IT STORES A VALUE TO THE VARUABLE 'x'                  SINGLE-LINE COMMENT
x = 1

#FIRST WE HAVE TO ASSIGN VALUE 1 TO X
#THEN WE PRINT THE VALUE OF X TO THE CONSOLE            MULTILINE COMMENT

print(x)   # PRINTS THE VALUE OF X TO THE CONSOLE       INLINE COMMENT [CODE AND COMMENT ON THE SAME LINE]


